import { TeamCode } from '@/types'

export const ALBUM = {
  TOTAL_STICKERS: 994,
  FWC_COUNT: 20,
  CC_COUNT: 14,
  STICKERS_PER_TEAM: 20,
  TEAM_COUNT: 48,
} as const

export const TEAM_NAMES: Record<TeamCode, string> = {
  ALG: 'Argélia',
  ARG: 'Argentina',
  AUS: 'Austrália',
  AUT: 'Áustria',
  BEL: 'Bélgica',
  BIH: 'Bósnia e Herzegovina',
  BRA: 'Brasil',
  CAN: 'Canadá',
  CIV: 'Costa do Marfim',
  COD: 'Rep. Dem. do Congo',
  COL: 'Colômbia',
  CPV: 'Cabo Verde',
  CRO: 'Croácia',
  CUW: 'Curaçao',
  CZE: 'República Tcheca',
  ECU: 'Equador',
  EGY: 'Egito',
  ENG: 'Inglaterra',
  ESP: 'Espanha',
  FRA: 'França',
  GER: 'Alemanha',
  GHA: 'Gana',
  HAI: 'Haiti',
  IRN: 'Irã',
  IRQ: 'Iraque',
  JOR: 'Jordânia',
  JPN: 'Japão',
  KOR: 'Coreia do Sul',
  KSA: 'Arábia Saudita',
  MAR: 'Marrocos',
  MEX: 'México',
  NED: 'Holanda',
  NOR: 'Noruega',
  NZL: 'Nova Zelândia',
  PAN: 'Panamá',
  PAR: 'Paraguai',
  POR: 'Portugal',
  QAT: 'Catar',
  RSA: 'África do Sul',
  SCO: 'Escócia',
  SEN: 'Senegal',
  SUI: 'Suíça',
  SWE: 'Suécia',
  TUN: 'Tunísia',
  TUR: 'Turquia',
  URU: 'Uruguai',
  USA: 'Estados Unidos',
  UZB: 'Uzbequistão',
}

export const TEAM_FLAGS: Record<TeamCode, string> = {
  ALG: '🇩🇿', ARG: '🇦🇷', AUS: '🇦🇺', AUT: '🇦🇹',
  BEL: '🇧🇪', BIH: '🇧🇦', BRA: '🇧🇷', CAN: '🇨🇦',
  CIV: '🇨🇮', COD: '🇨🇩', COL: '🇨🇴', CPV: '🇨🇻',
  CRO: '🇭🇷', CUW: '🇨🇼', CZE: '🇨🇿', ECU: '🇪🇨',
  EGY: '🇪🇬', ENG: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', ESP: '🇪🇸', FRA: '🇫🇷',
  GER: '🇩🇪', GHA: '🇬🇭', HAI: '🇭🇹', IRN: '🇮🇷',
  IRQ: '🇮🇶', JOR: '🇯🇴', JPN: '🇯🇵', KOR: '🇰🇷',
  KSA: '🇸🇦', MAR: '🇲🇦', MEX: '🇲🇽', NED: '🇳🇱',
  NOR: '🇳🇴', NZL: '🇳🇿', PAN: '🇵🇦', PAR: '🇵🇾',
  POR: '🇵🇹', QAT: '🇶🇦', RSA: '🇿🇦', SCO: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  SEN: '🇸🇳', SUI: '🇨🇭', SWE: '🇸🇪', TUN: '🇹🇳',
  TUR: '🇹🇷', URU: '🇺🇾', USA: '🇺🇸', UZB: '🇺🇿',
}

export const GROUPS: { label: string; teams: TeamCode[] }[] = [
  { label: 'Grupo A', teams: ['MEX', 'RSA', 'KOR', 'CZE'] },
  { label: 'Grupo B', teams: ['CAN', 'SUI', 'QAT', 'BIH'] },
  { label: 'Grupo C', teams: ['BRA', 'MAR', 'SCO', 'HAI'] },
  { label: 'Grupo D', teams: ['USA', 'PAR', 'AUS', 'TUR'] },
  { label: 'Grupo E', teams: ['GER', 'CUW', 'CIV', 'ECU'] },
  { label: 'Grupo F', teams: ['NED', 'JPN', 'SWE', 'TUN'] },
  { label: 'Grupo G', teams: ['BEL', 'EGY', 'IRN', 'NZL'] },
  { label: 'Grupo H', teams: ['ESP', 'CPV', 'KSA', 'URU'] },
  { label: 'Grupo I', teams: ['FRA', 'SEN', 'IRQ', 'NOR'] },
  { label: 'Grupo J', teams: ['ARG', 'ALG', 'AUT', 'JOR'] },
  { label: 'Grupo K', teams: ['POR', 'COD', 'UZB', 'COL'] },
  { label: 'Grupo L', teams: ['ENG', 'CRO', 'PAN', 'GHA'] },
]

export const TEAMS_ORDERED: TeamCode[] = GROUPS.flatMap((g) => g.teams)